name: wam2layers
channels:
  - defaults
dependencies:
  - python=3
  - cartopy
  - numpy
  - scipy
  - netcdf4
  - matplotlib
  - pyyaml
  - xarray
  - ipython


# dev: sphinx, sphinx_rtd_theme, myst-parser, cffconvert, black, isort, ...
