name: wam2layers
channels:
  - defaults
dependencies:
  - python=3
  - cartopy
  - numpy
  - scipy
  - netcdf4
  - matplotlib
  - pyyaml
  - xarray
  # - ipython
  # - sphinx
  # - sphinx_rtd_theme
  # - myst-nb
  # - black
  # - isort
  # - cffconvert
