name: wam2layers
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - cartopy
  - numpy
  - scipy
  - netcdf4
  - matplotlib
  - pyyaml
  - xarray
  - ipython
  - sphinx
  - sphinx_rtd_theme
  - black
  - isort
  - pip:
    - myst-nb
    - cffconvert
