title: "Q&A"
labels: "Questions and answers"
body:
  - type: markdown
    attributes:
      value: |
        Welcome to WAM2layers! 

        If you're new here, please check our [readme](https://github.com/WAM2layers/WAM2layers), 
        [documentation](https://wam2layers.readthedocs.io/en/latest/) first. 
      
        Still have questions? Please introduce yourself if you are a new user, and ask your question as clearly as possible. 
        We try to keep an eye on this forum and we hope that everyone who benefits from it will do the same, so help can come as quickly as possible.