body:
  - type: markdown
    attributes:
      value: |
        Welcome to WAM2layers!

        If you're new here, please check our [readme](https://github.com/WAM2layers/WAM2layers#readme) and [documentation](https://wam2layers.readthedocs.io/en/latest/) first.

        Perhaps, your question is related to an outstanding issue, please check [issues](https://github.com/WAM2layers/WAM2layers/issues) first.
  - type: textarea
    attributes:
      label: My question
      description: "Please introduce yourself if you are a new user, and ask your question as clearly as possible. We try to keep an eye on this forum and we hope that everyone who benefits from it will do the same, so help can come as quickly as possible."
    validations:
      required: true
