name: New Issue
description: List an issue for the improvement of WAM2layers
body:
  - type: markdown
    value: "If you have a question, idea or want to engage with the community, check 'Discussions' and the flowchart in the readme first. If you want to contribute to the development and know what you are doing, you are welcome to open a new issue. In any case please introduce yourself if you are a new user."
    validations:
      required: true
