name: New Issue
description: List an issue for the improvement of WAM2layers
body:
  - type: markdown
    attributes:
      description: |
      Welcome to WAM2layers! 

      If you're new here, please check our [readme](https://github.com/WAM2layers/WAM2layers), 
      [documentation](https://wam2layers.readthedocs.io/en/latest/) 
      and [discussion forum](https://github.com/WAM2layers/WAM2layers/discussions) first. 
      
      The discussion forum is a good place to ask questions, discuss ideas, or get to know the community. 
      Please introduce yourself if you are a new user
    validations:
      required: true