# Paths (relative to root of repo)
filename_template: sample_data/input_data/ERA5_{year}-{month:02d}-{day:02d}{levtype}_{variable}.nc
region: sample_data/source_region.nc
preprocessed_data_folder: /tmp/wam2layers/sample/preprocessed_data
output_folder: /tmp/wam2layers/sample/output_data

# Dates
preprocess_start_date: "2021-07-15T01:00"
preprocess_end_date: "2021-07-15T23:00"
track_start_date: "2021-07-15T01:00"
track_end_date: "2021-07-15T23:00"
event_start_date: "2021-07-15T10:00"
event_end_date: "2021-07-15T23:00"

# Time
input_frequency: "1h"
target_frequency: "10min"
output_frequency: "3h"

# Levels
level_type: model_levels
levels: [20,40,60,80,90,95,100,105,110,115,120,123,125,128,130,131,132,133,134,135,136,137]

# Model settings
log_level: info
restart: False
periodic_boundary: false
kvf: 3
chunks: null
