# General
preprocessed_data_folder: https://opendap.4tu.nl/thredds/dodsC/data2/djht/00f7fa45-899e-4573-ae23-234f6c5193d0/1
output_folder: output/eiffel
tracking_direction: backward

# Preprocessing (not used here, but fields cannot be empty)
filename_template: ERA5_{year}-{month:02d}-{day:02d}{levtype}_{variable}.nc
preprocess_start_date: "2021-07-01T00:00"
preprocess_end_date: "2021-07-15T00:00"
level_type: model_levels
levels: [20,40,60,80,90,95,100,105,110,115,120,123,125,128,130,131,132,133,134,135,136,137]

# Tracking
#tracking_domain: null  # use full domain of preprocessed data
tracking_domain: [-50, 30, 30, 60]  # use subdomain of preprocessed data # west, south, east, north 
tracking_start_date: "2021-07-01T00:00"
tracking_end_date: "2021-07-15T00:00"

# Tagging
#tagging_region: region-eiffel.nc # does not work, because this nc-file has 0.25 degree, use box instead
tagging_region: [4, 49, 9, 52]  # alternative to mask file # west, south, east, north
tagging_start_date: "2021-07-13T00:00"
tagging_end_date: "2021-07-15T00:00"

input_frequency: "1h"
timestep: 600
output_frequency: "1D"
restart: False
periodic_boundary: false
kvf: 3
