name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install gdown
      - name: Test installation
        run: |
          pip install .
          wam2layers --help
      - name: Try to get sample data from cache
        id: cache-sample-data
        uses: actions/cache@v3
        with:
          path: ~/wam2layers
          key: wam2layers_sample_data
      - if: ${{ steps.cache-sample-data.outputs.cache-hit != 'true' }}
        name: Download sample data if not available in cache
        run: |
          gdown -O ~/wam2layers --folder https://rebrand.ly/wam2layers-example-data
      - name: Run test case
        run: |
          cd ~/wam2layers/floodcase_202107
          wam2layers backtrack floodcase_202107.yaml
